# script to take tfrecord files generated by VoTT and put 20% into a val folder
# with remainder used for training
import os
TRAINPATH= os.getcwd() + "/train/"
VALPATH= os.getcwd() + "/val/"
i = 1
t = 0
v = 0 
for f in os.listdir(os.getcwd()):
    if f.find("tfrecord") != -1:
        if i % 5 == 0 
            dst = TRAINPATH + f 
            t += 1
        else:
            dst = VALPATH + f
            v += 1 
        os.rename(os.getcwd() + "/" + f, dst) 
        i += 1 
print("Script completed, " + str(t) + " training files and " + str(v) + " val files")

